// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using FluentWebApplication.Models;
using Microsoft.EntityFrameworkCore;

namespace FluentWebApplication.Data;

public partial class Context : DbContext
{
    public Context()
    {
    }

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Person> Person { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Person>(entity =>
        {
            entity.Property(e => e.EmailAddress).IsRequired();
            entity.Property(e => e.FirstName).IsRequired();
            entity.Property(e => e.LastName).IsRequired();
        });

        modelBuilder.Entity<Person>().HasData(
            new Person()
            {
                PersonId = 1,
                FirstName = "Karen",
                LastName = "Payne",
                EmailAddress = "payne@comcast.net"
            },
            new Person()
            {
                PersonId = 2,
                FirstName = "Bob",
                LastName = "Smith",
                EmailAddress = "BillyBob@bear.com"
            }
        );

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}