// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace NorthWindLibrary.Models;

public partial class Categories
{
    public int CategoryId { get; set; }
    public string CategoryName { get; set; }
    public virtual ICollection<Products> Products { get; } = new List<Products>();
}