// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable


namespace NorthWindLibrary.Models;

public partial class Products
{
    public int ProductId { get; set; }
    public string ProductName { get; set; }
    public int? SupplierId { get; set; }
    public int? CategoryId { get; set; }
    public decimal? UnitPrice { get; set; }
    public virtual Categories Category { get; set; }
    public virtual Suppliers Supplier { get; set; }
}