// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NorthWindLibrary.Models;

namespace NorthWindLibrary.Data.Configurations;

public partial class ProductsConfiguration : IEntityTypeConfiguration<Products>
{
    public void Configure(EntityTypeBuilder<Products> entity)
    {
        entity.HasKey(e => e.ProductId);

        entity.HasIndex(e => e.CategoryId, "IX_Products_CategoryID");

        entity.HasIndex(e => e.SupplierId, "IX_Products_SupplierID");

        entity.Property(e => e.ProductId).HasColumnName("ProductID");
        entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
        entity.Property(e => e.ProductName)
            .IsRequired()
            .HasMaxLength(40);
        entity.Property(e => e.SupplierId).HasColumnName("SupplierID");
        entity.Property(e => e.UnitPrice).HasColumnType("money");

        entity.HasOne(d => d.Category).WithMany(p => p.Products)
            .HasForeignKey(d => d.CategoryId)
            .HasConstraintName("FK_Products_Categories");

        entity.HasOne(d => d.Supplier).WithMany(p => p.Products)
            .HasForeignKey(d => d.SupplierId)
            .HasConstraintName("FK_Products_Suppliers");

        OnConfigurePartial(entity);
    }

    partial void OnConfigurePartial(EntityTypeBuilder<Products> entity);
}