// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

#nullable disable

using Microsoft.EntityFrameworkCore;
using TaxpayerLibrary.Data.Configurations;
using TaxpayerLibrary.Models;

namespace TaxpayerLibrary.Data;

public partial class Context : DbContext
{
    public Context()
    {
    }

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Taxpayer> Taxpayer { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new TaxpayerConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
